services:
  app:
    container_name: nourgaser-com
    image: nourgaser-com:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # nginx-proxy routing.
      VIRTUAL_HOST: ${VIRTUAL_HOST:-me.nourgaser.com, nourgaser.com, www.nourgaser.com}
      VIRTUAL_PORT: 80

      # Let's Encrypt provisioning.
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST:-me.nourgaser.com, nourgaser.com, www.nourgaser.com}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-dev@nourgaser.com}
    restart: unless-stopped
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
