name: Deploy Application

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and deploy
        env:
          VIRTUAL_HOST: ${{ vars.VIRTUAL_HOST }}
          LETSENCRYPT_HOST: ${{ vars.LETSENCRYPT_HOST }}
          LETSENCRYPT_EMAIL: ${{ vars.LETSENCRYPT_EMAIL }}
          RAWG_API_KEY: ${{ secrets.RAWG_API_KEY }}
        run: docker compose up -d --build --force-recreate
